#!/usr/bin/ruby
 
require 'rubygems'
require 'json'
require 'net/http'
require 'uri'
require 'time'

class TwitterBackup
 
  def backup(username)
    url = URI::parse('http://twitter.com')
 
    page = 200
    loop do
      req = Net::HTTP::Get.new("/statuses/user_timeline.json?screen_name=#{username}&page=#{page}")
      res = Net::HTTP.start(url.host, url.port) {|http| http.request(req) }
 
      if res.body.length > 2
        begin
          response_as_json = JSON.parse(res.body)
          process_response(response_as_json)
          page += 1 
          sleep 10
        rescue
          sleep 30
        end
      else 
        puts res.body
        break
      end
    end
  end
 
  protected
    def process_response(response_json)
        response_json.each do |tweet|
          puts "#{Time.parse(tweet['created_at']).strftime("%A %d %B %Y at %I:%M%p")}\t#{tweet['text']}\t#{tweet['source']}\t#{tweet['in_reply_to_screen_name']}"
        end
    end
end
 
TwitterBackup.new.backup(ARGV[0])